### ISSUE TITLE
User Guide: `User` is not clickable

### ISSUE THREAD

**Issue by ffaf1** [profanity-im/profanity-im.github.io#108]
To replicate:
- check a page from the Quick star guide (e.g. [this one](https://profanity-im.github.io/guide/0140/rooms.html))
- decide you want to go back to the User Guide main page
- click on "User Guide" (black font on red background)
- the "User" part of "User Guide" is not clickable

Expected:
- "User Guide" is clickable in its entirety

**Comment by jubalh** [comment]
Will you create a PR for this?
