### ISSUE TITLE
Update command reference - tls legacy

### ISSUE THREAD

**Issue by pasis** [profanity-im/profanity-im.github.io#17]
Profanity was updated with `/connect ... tls legacy` and `/account ... set tls legacy`. Add this info to the command reference.

Just a thought: toc_fragment.html and main_fragment.html should be generated automatically from the Profanity inner help.

**Comment by jubalh** [comment]
> Profanity was updated with /connect ... tls legacy and /account ... set tls legacy. Add this info to the command reference.

Done at: https://profanity-im.github.io/reference.html#connect
