### ISSUE TITLE
shasums truncated on small viewports

### ISSUE THREAD

**Issue by Ppjet6** [profanity-im/profanity-im.github.io#33]
## Steps to reproduce

- Reduce the viewport to something between 1592 and 838 px.
  (Easily doable in Firefox with the Responsive Design Mode, Ctrl+Shift+M. Chromium has similar features)

## What happens

Shasums get truncated.

![Screenshot_2019-08-09 Profanity, a console based XMPP client - Home](https://user-images.githubusercontent.com/138302/62759566-2ff27380-ba71-11e9-904b-8444dc184cd4.png)

## Expected behaviour

Shasums are not truncated.

Maybe this can be done letting the browser wrap them, with something like `overflow-wrap: break-word` in CSS.

**Comment by jubalh** [comment]
@MattyBalaam could you give a look here too?

**Comment by MattyBalaam** [comment]
I‘m going to do a little rewrite around the compilation here. It‘s using some rather dated tools: A Compass flavour of SASS being run via Ruby… 

I‘ve started an initial stage of reriting the tooling so the SCSS styles are compiled by Webpack and  Compass mixins are removed, with post-css/autoprefixer handling browser support. If things go well could be done in the next week depending on when I get time.

As a second stage I‘d then like to move away from SCSS to plain CSS (albeit with the latest features and using post-css/autoprefixer for compatability)

**Comment by jubalh** [comment]
I have almost no idea about most web tech. But it sounds good! :) :)
