### ISSUE TITLE
Page "Complete command reference" broken

### ISSUE THREAD

**Issue by Misaflo** [profanity-im/profanity-im.github.io#39]
Hello,

The page [Complete command reference](https://profanity-im.github.io/guide/070/reference.html) is broken.
It must be since the removing of jquery (the page still use jquery).

**Comment by jubalh** [comment]
Thanks for the report.
I saw so too this morning.

Didn't have time to fix it yet.

If you want you could give it a try and create a PR! :)

**Comment by jubalh** [comment]
Or @MattyBalaam could take a look? Seems like the last PR caused this.

**Comment by MattyBalaam** [comment]
Sorry I missed that.

Looks like a strange use of using jQuery to me for it to load partial content in that way ;)

I wonder if instead of re-inventing the wheel for the wrong purpose it might be better to use some kind of build step to include partials like this?

**Comment by MattyBalaam** [comment]
Quick solution would be just to include jquery on this page only, possibly from a CDN.

**Comment by jubalh** [comment]
Thanks guys
