### ISSUE TITLE
CNAME?

### ISSUE THREAD

**Issue by Neustradamus** [profanity-im/profanity-im.github.io#60]
It is possible in GitHub to add;
- The CNAME file to profanity.im?
- Settings in DNS Zone of the domain name?
- Enable https too?
- Verify the domain name?

Thanks in advance.

**Comment by jubalh** [comment]
Just use https://profanity-im.github.io/. You have https and everything there.
I'm not certain @boothj5 plans to sponsor profanity.im forever. AFAIK it was an option for him to drop the domain and we just rely on GH pages.

**Comment by Neustradamus** [comment]
1/ The CNAME file (with only: profanity.im) is needed in https://github.com/profanity-im/profanity-im.github.io
2/ DNS Zone of profanity.im -> And add GitHub settings that you will have here:
- https://github.com/profanity-im/profanity-im.github.io/settings "GitHub Pages" section + Enforce HTTPS
3/ https://github.com/organizations/profanity-im/settings/profile URL -> https://profanity-im.github.io/ -> http://profanity.im/
4/ https://github.com/organizations/profanity-im/settings/domains -> "Add a domain" -> profanity.im
5/ Add TXT informations in DNS Zone

And it will be perfect.

cc: @boothj5.

Thanks in advance.

**Comment by Neustradamus** [comment]
@boothj5: Can you look to add the CNAME file with profanity.im
And look in repository options and organization options?
And add in DNS Zone informations?

One place, easy update etc.

Thanks in advance.

**Comment by Neustradamus** [comment]
@boothj5, @jubalh: Have you seen for the CNAME file into this repository?
GitHub Pages: https://github.com/profanity-im/profanity-im.github.io/settings
- https://docs.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site

**Comment by jubalh** [comment]
Just use profanity-im.github.io.
On all sites I found I updated the link to the offical page to be profanity-im.github.io.
Also in profanity itself we post this link. Also on GitHub. So just use it.

**Comment by Neustradamus** [comment]
@boothj5: Can you remove the domain name?
It is not needed, @jubalh prefers profanity-im.github.io.
It is very hard to explain in this team.
Thanks in advance.

**Comment by jubalh** [comment]
> It is very hard to explain in this team.
:D

My friend. Nothing is hard to explain in this team. The problem is that you run around projects telling them what to do. But most of they time the projects know exactly what to do. They also know their inner workings and conditions for things to be that way.
